spring:
  application.name: springboot2-resilience4j

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

---
spring:
  profiles: chaos-monkey

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    chaosmonkey:
      enabled: true

chaos:
  monkey:
    enabled: true
    #    watcher:
    #      service: false
    assaults:
      level: 2
      latency-active: true
      latency-range-start: 1000
      latency-range-end: 2000
      exceptions-active: true
      #      exception:
      #        type: java.lang.RuntimeException
      #        arguments:
      #          - className: "java.lang.String"
      #            value: "test exception"
      watched-custom-services: >
#        com.kakao.pay.account.thrift.AccountService.Iface.findPayAccountById,
#        com.kakaopay.jumak.infra.payaccount.client.PayAccountClient.getAccountId,
#        com.kakaopay.jumak.chaosmonkey.service.HelloService.hello