spring:
  profiles:
    active: local
    include: >
      library-jpa
  mvc:
    static-path-pattern: /static/** # 정적 리소스 매핑 URL 패턴, '기본값: /**'
  resources:
    static-locations: classpath:/static/ # 정적 리소스 위치 값, '기본값: classpath:/static/'

springdoc:
  swagger-ui:
    path: /swagger-ui.html # http://server:port/swagger-ui.html 또는 http://server:port/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

---
spring:
  profiles: local

---
spring:
  profiles: production

springdoc:
  api-docs:
    enabled: false
