rootProject.name = "spring-j"

include(":aop-reflection")
include(":async")
include(":cache")
include(":core")
include(":jpa")
include(":mvc-rest")
include(":netty")
include(":netty:netty-server")
include(":netty:netty-client")
include(":reactive")
include(":reactive-websocket")
include(":reactive-websocket:server")
include(":reactive-websocket:client")
include(":resilience4j")
include(":ws-chat")
