{
 "title": "MySQL Connector",
 "description": "Monitoring Dashboard for Debezium MySQL connector",
 "tags": [
  "mysql",
  "debezium"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "debezium_metrics_BinlogPosition"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "debezium_metrics_BinlogPosition"
    }
   },
   {
    "name": "context",
    "label": "context",
    "query": {
     "query": "debezium_metrics_MilliSecondsSinceLastEvent"
    }
   },
   {
    "name": "plugin",
    "label": "plugin",
    "query": {
     "query": "debezium_metrics_BinlogPosition"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "debezium_metrics_BinlogPosition"
    }
   }
  ]
 },
 "panels": [
  { "title": "Binlog Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total NumberOf EventsSeen",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Skipped Events",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfSkippedEvents{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Events Filtered",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "debezium_metrics_Connected{context=\"streaming\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Binlog Position",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_BinlogPosition{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "GTID Enabled",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_IsGtidModeEnabled{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Committed Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfCommittedTransactions{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf RolledBack Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfRolledBackTransactions{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Not WellFormed Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfNotWellFormedTransactions{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\r"
    }
   ]
  },
  {
   "title": "Seconds Behind Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_SecondsBehindMaster{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Seconds Since LastEvent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_SecondsSinceLastEvent{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Connects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_Connected{context=\"streaming\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "MilliSeconds Behind Source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsBehindSource{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Large Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfLargeTransactions{context=\"streaming\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  { "title": "Snapshot Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Tablecount",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_TotalTableCount{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Remaining Tales",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_RemainingTableCount{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Holding GlobalLock",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_HoldingGlobalLock{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotAborted{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotCompleted{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotDurationInSeconds{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Events Filtered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "MilliSeconds Since LastEvent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\r"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Erroneous Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfErroneousEvents{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\r"
    }
   ]
  },
  {
   "title": "Total NumberOf Events Seen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"snapshot\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  { "title": "Schema History Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Changes Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_ChangesRecovered{context=\"schema-history\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Recovery StartTime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 55 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "debezium_metrics_RecoveryStartTime{context=\"schema-history\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Since Last AppliedChange",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 55 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastAppliedChange{context=\"schema-history\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Since Last RecoveredChange",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 55 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastRecoveredChange{context=\"schema-history\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Changes Applied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_ChangesApplied{context=\"schema-history\",instance=\"$instance\",job=\"$job\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  }
 ]
}